const header=document.querySelector('.topbar'),menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
const finalTouch=document.createElement('link');finalTouch.rel='stylesheet';finalTouch.href='final-touch.css';document.head.appendChild(finalTouch);
const launchRefine=document.createElement('link');launchRefine.rel='stylesheet';launchRefine.href='launch-refine.css?v=20260822-1';document.head.appendChild(launchRefine);
const launchPolish=document.createElement('link');launchPolish.rel='stylesheet';launchPolish.href='launch3-polish.css?v=20260822-1';document.head.appendChild(launchPolish);
const presentationFinish=document.createElement('link');presentationFinish.rel='stylesheet';presentationFinish.href='presentation2.css?v=20260828-4';document.head.appendChild(presentationFinish);
const updateHeaderTone=()=>{header?.classList.toggle('scrolled',scrollY>30);const hero=document.querySelector('.hero,.pagehero'),closing=document.querySelector('.hub-tease,.contact');const start=(hero?.offsetHeight||innerHeight)*.62,end=(hero?.offsetHeight||innerHeight)*1.02;let light=Math.max(0,Math.min(1,(scrollY-start)/(end-start)));if(closing){const closingStart=closing.offsetTop-innerHeight*.35,closingEnd=closing.offsetTop+innerHeight*.15;light*=1-Math.max(0,Math.min(1,(scrollY-closingStart)/(closingEnd-closingStart)))}header?.style.setProperty('--header-light',`${light*100}%`)};addEventListener('scroll',updateHeaderTone,{passive:true});addEventListener('resize',updateHeaderTone,{passive:true});updateHeaderTone();
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.addEventListener('click',()=>nav.classList.remove('open'));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)});
const serviceData=[
{code:'WHEN THE REAL QUESTION IS STILL UNCLEAR',title:'Decision framing',copy:'Useful when a project, requirement or operational problem feels important but the exact decision is still blurred.',meta:['clarify the outcome, evidence, constraints and realistic options.','a question brief, option map and decision-ready next-step note.','a focused orientation followed by a scoped short assignment.'],items:['Frame the decision that actually needs to be made','Identify missing evidence and connected interfaces','Compare practical routes and consequences','Define what the next responsible commitment requires']},
{code:'BEFORE BUDGETS, SPECIFICATIONS OR AWARDS HARDEN',title:'Project and procurement strategy',copy:'Useful when requirements, budgets, procurement routes or vendor approaches need to be tested before commitment.',meta:['connect the requirement, market route, lifecycle cost and acceptance logic.','a procurement-ready question set, option comparison and decision gates.','a defined review or strategy assignment matched to the procurement stage.'],items:['Interrogate the requirement and delivery route','Compare procurement and phasing options','Prepare vendor questions and evaluation logic','Define evidence, acceptance and handover needs']},
{code:'WHEN A PROPOSAL LOOKS CONVINCING BUT CONSEQUENCES REMAIN HIDDEN',title:'Technical–commercial review',copy:'Useful before approving equipment, reports, bids, changes or claims whose technical and commercial effects are connected.',meta:['normalize assumptions, deviations, interfaces, risks and whole-life consequences.','a traceable review, clarification register and plain-language decision brief.','a bounded independent review with named inputs and exclusions.'],items:['Review specifications, reports and offers','Connect technical deviations to commercial effects','Name missing evidence and unresolved interfaces','Prepare questions and conditions before approval']},
{code:'WHEN KNOWLEDGE MUST OUTLIVE ONE PROJECT OR ONE TEAM',title:'Institutional planning and knowledge systems',copy:'Useful when repeated decisions, disconnected files or unclear ownership are slowing an organization down.',meta:['structure decisions, roles, templates, review triggers and reusable knowledge.','a practical governance map, decision logbook and reusable working formats.','a diagnostic workshop followed by a staged implementation roadmap.'],items:['Map how decisions currently move','Design clear ownership and review points','Create reusable records and proposal structures','Turn project learning into institutional memory']}
];
document.querySelectorAll('.service-tabs button').forEach((btn,i)=>{btn.addEventListener('click',()=>selectService(i));btn.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const buttons=[...document.querySelectorAll('.service-tabs button')];const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(i+(event.key==='ArrowDown'||event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();selectService(next)})});
function selectService(i){const buttons=[...document.querySelectorAll('.service-tabs button')];buttons.forEach((x,j)=>{x.classList.toggle('active',j===i);x.setAttribute('aria-selected',String(j===i))});const d=serviceData[i],box=document.querySelector('.service-display');box.animate([{opacity:.45,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:180});box.querySelector('.service-code').textContent=d.code;box.querySelector('h3').textContent=d.title;box.querySelector('.service-copy').textContent=d.copy;const labels=['We help','You receive','Typical first step'];box.querySelector('.service-meta').innerHTML=d.meta.map((x,j)=>`<span><b>${labels[j]}</b> ${x}</span>`).join('');box.querySelector('ul').innerHTML=d.items.map(x=>`<li>${x}</li>`).join('')}
document.querySelectorAll('.manifesto article').forEach(x=>{const activate=()=>{document.querySelectorAll('.manifesto article').forEach(y=>y.classList.remove('active'));x.classList.add('active')};x.addEventListener('mouseenter',activate);x.addEventListener('focus',activate);x.addEventListener('click',activate)});
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
const reframeControl=document.querySelector('.reframe-control');reframeControl?.addEventListener('click',()=>{const answer=document.querySelector('#reframe-answer'),open=!answer.classList.contains('open');answer.classList.toggle('open',open);reframeControl.setAttribute('aria-expanded',String(open));reframeControl.querySelector('b').textContent=open?'−':'+'});
document.querySelectorAll('.principle-cards article').forEach(card=>{const toggle=()=>{const open=card.getAttribute('aria-expanded')!=='true';card.setAttribute('aria-expanded',String(open))};card.addEventListener('click',toggle);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}})});
const progressLinks=[...document.querySelectorAll('.page-progress a')],progressSections=progressLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);if(progressSections.length){const progressObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)progressLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+entry.target.id))}),{rootMargin:'-35% 0px -55%'});progressSections.forEach(section=>progressObserver.observe(section))}
let backTop=document.querySelector('.back-top');if(!backTop){document.body.insertAdjacentHTML('beforeend','<a class="back-top global-back-top" href="#main" aria-label="Back to top">↑</a>');backTop=document.querySelector('.back-top')}addEventListener('scroll',()=>backTop?.classList.toggle('visible',scrollY>innerHeight),{passive:true});
document.querySelectorAll('.topbar nav a').forEach(link=>{const label=link.textContent.trim();if(/How we work/i.test(label)){link.childNodes[0].textContent='Method '}if(/Why we began/i.test(label))link.textContent='About';if(/Start a conversation/i.test(label)){link.childNodes[0].textContent='Bring us a question '}});
document.querySelectorAll('footer nav').forEach(footerNav=>{[...footerNav.querySelectorAll('a')].forEach(link=>{if(!/^(Ecosystem|Privacy|Terms|Staff Vault)$/i.test(link.textContent.trim()))link.remove()})});
document.querySelectorAll('.mobile-dock').forEach(dock=>dock.innerHTML='<a href="hub.html"><i>⌁</i><span>Ecosystem</span></a><a class="dock-main" href="index.html#contact"><i>↗</i><span>Ask Anchor Point</span></a><a href="evidence.html#demonstrations"><i>◇</i><span>Examples</span></a>');
document.querySelector('.contact-card')?.insertAdjacentHTML('beforeend','<p style="font:italic .95rem/1.5 Playfair Display;color:var(--gold2);border-top:1px solid #ffffff18;padding-top:18px">A first conversation costs curiosity—not a procurement file. Start small. We are listening.</p>');
const principles=document.querySelector('.principles');if(document.querySelector('.hero')&&principles&&!document.querySelector('.renaissance')){principles.insertAdjacentHTML('afterend',`<section class="renaissance"><div class="renaissance-image" role="img" aria-label="Technical linework connecting marine, structural, mechanical, electrical, water and flight engineering"></div><div class="renaissance-copy reveal"><p class="kicker"><span></span> Curiosity is infrastructure</p><h2>A machine begins<br>as a question.</h2><p>Real projects do not respect departmental boundaries. Water affects structures. Operations affect machinery. People affect systems. Cost affects every option.</p><p>We observe closely, sketch freely, test honestly and connect what is usually considered separately.</p><p class="renaissance-note">A quiet Renaissance instinct: understand the world by drawing its connections.</p><a class="pill gold" href="#contact">Bring the napkin sketch, too ↗</a></div></section>`);document.querySelectorAll('.renaissance .reveal').forEach(el=>reveal.observe(el));}
const ecosystemPool=[
['Scientific calculator','scientific.html','Expressions · functions'],['Conversion desk','convert.html','Units · visible method'],['Civil calculations','hub.html#library','Area · volume · slope'],['Mechanical calculations','hub.html#library','Torque · power · motion'],['Marine calculations','hub.html#library','Speed · hull · displacement'],['Electrical calculations','hub.html#library','Power · voltage · current'],['Energy calculations','hub.html#library','Flow · head · efficiency'],['Systems calculations','hub.html#library','Rate · capacity · availability'],['Materials calculations','hub.html#library','Stress · strain · welds'],['Bangladesh libraries','hub.html#resources','Official discovery routes'],['Authoritative sources','hub.html#resources','Standards · public data'],['Open engineering texts','hub.html#resources','Theory · worked foundations'],['Scientific constants','scientific.html','π · e · functions'],['Angle functions','scientific.html','sin · cos · tan'],['Pressure conversion','convert.html','Pressure · force · area'],['Flow conversion','convert.html','Volume · time'],['Energy conversion','convert.html','Work · heat · power'],['Length conversion','convert.html','Metric · imperial'],['Temperature conversion','convert.html','Celsius · Fahrenheit'],['Engineering library','hub.html#library','50 visible calculations']
];
const ecosystemTools=document.querySelector('.ecosystem-tools');if(ecosystemTools){let ecosystemOffset=0;const renderEcosystem=()=>{const chosen=Array.from({length:6},(_,i)=>ecosystemPool[(ecosystemOffset+i*3)%ecosystemPool.length]);ecosystemTools.innerHTML=chosen.map(([label,href,detail])=>`<a class="ecosystem-tool" href="${href}"><span>${label}</span><small>${detail}</small></a>`).join('');ecosystemOffset=(ecosystemOffset+1)%ecosystemPool.length};renderEcosystem();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(renderEcosystem,6500)}
const utilityLinks=[...document.querySelectorAll('.utility-bar [data-utility]')];if(utilityLinks.length){const setUtilityActive=key=>utilityLinks.forEach(link=>{const active=link.dataset.utility===key;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')});setUtilityActive('examples');const utilitySections=[['#demonstration','examples'],['#thinking','examples'],['#curiosity','examples'],['#ecosystem','ecosystem'],['#contact','contact']].map(([selector,key])=>[document.querySelector(selector),key]).filter(([section])=>section);const utilityObserver=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible){const match=utilitySections.find(([section])=>section===visible.target);if(match)setUtilityActive(match[1])}},{rootMargin:'-28% 0px -52% 0px',threshold:[0,.15,.35,.6]});utilitySections.forEach(([section])=>utilityObserver.observe(section))}
document.querySelectorAll('a[href^="mailto:"]').forEach(link=>{if(!/email us/i.test(link.textContent))link.href=location.pathname.endsWith('index.html')||document.body.classList.contains('v30-review')?'#contact':'index.html#contact'});
document.querySelectorAll('.pill.gold').forEach(button=>{button.querySelectorAll('img,b').forEach(mark=>mark.remove());[...button.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).forEach(node=>node.textContent=node.textContent.replace(/\s*↗\s*/g,' ').trim())});

