document.documentElement.classList.add('js-enabled');
const header=document.querySelector('.topbar'),menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
const finalTouch=document.createElement('link');finalTouch.rel='stylesheet';finalTouch.href='final-touch.css';document.head.appendChild(finalTouch);
const launchRefine=document.createElement('link');launchRefine.rel='stylesheet';launchRefine.href='launch-refine.css?v=20260822-1';document.head.appendChild(launchRefine);
const launchPolish=document.createElement('link');launchPolish.rel='stylesheet';launchPolish.href='launch3-polish.css?v=20260822-1';document.head.appendChild(launchPolish);
const finalSystem=document.createElement('link');finalSystem.rel='stylesheet';finalSystem.href='final-owner-system.css?v=20260826-1';document.head.appendChild(finalSystem);
document.body.insertAdjacentHTML('afterbegin','<div class="engineering-thread" aria-hidden="true"><span></span><i></i></div>');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
addEventListener('scroll',()=>document.documentElement.style.setProperty('--page-progress',Math.min(1,scrollY/(document.documentElement.scrollHeight-innerHeight))),{passive:true});
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.addEventListener('click',()=>nav.classList.remove('open'));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)});
const serviceData=[
{code:'WHEN THE REAL QUESTION IS STILL UNCLEAR',title:'Decision framing',copy:'Useful when a project, requirement or operational problem feels important but the exact decision is still blurred.',meta:['clarify the outcome, evidence, constraints and realistic options.','a question brief, option map and decision-ready next-step note.','a focused orientation followed by a scoped short assignment.'],items:['Frame the decision that actually needs to be made','Identify missing evidence and connected interfaces','Compare practical routes and consequences','Define what the next responsible commitment requires']},
{code:'BEFORE BUDGETS, SPECIFICATIONS OR AWARDS HARDEN',title:'Project and procurement strategy',copy:'Useful when requirements, budgets, procurement routes or vendor approaches need to be tested before commitment.',meta:['connect the requirement, market route, lifecycle cost and acceptance logic.','a procurement-ready question set, option comparison and decision gates.','a defined review or strategy assignment matched to the procurement stage.'],items:['Interrogate the requirement and delivery route','Compare procurement and phasing options','Prepare vendor questions and evaluation logic','Define evidence, acceptance and handover needs']},
{code:'WHEN A PROPOSAL LOOKS CONVINCING BUT CONSEQUENCES REMAIN HIDDEN',title:'Technical–commercial review',copy:'Useful before approving equipment, reports, bids, changes or claims whose technical and commercial effects are connected.',meta:['normalize assumptions, deviations, interfaces, risks and whole-life consequences.','a traceable review, clarification register and plain-language decision brief.','a bounded independent review with named inputs and exclusions.'],items:['Review specifications, reports and offers','Connect technical deviations to commercial effects','Name missing evidence and unresolved interfaces','Prepare questions and conditions before approval']},
{code:'WHEN KNOWLEDGE MUST OUTLIVE ONE PROJECT OR ONE TEAM',title:'Institutional planning and knowledge systems',copy:'Useful when repeated decisions, disconnected files or unclear ownership are slowing an organization down.',meta:['structure decisions, roles, templates, review triggers and reusable knowledge.','a practical governance map, decision logbook and reusable working formats.','a diagnostic workshop followed by a staged implementation roadmap.'],items:['Map how decisions currently move','Design clear ownership and review points','Create reusable records and proposal structures','Turn project learning into institutional memory']}
];
document.querySelectorAll('.service-tabs button').forEach((btn,i)=>{btn.addEventListener('click',()=>selectService(i));btn.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const buttons=[...document.querySelectorAll('.service-tabs button')];const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(i+(event.key==='ArrowDown'||event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();selectService(next)})});
function selectService(i){const buttons=[...document.querySelectorAll('.service-tabs button')];buttons.forEach((x,j)=>{x.classList.toggle('active',j===i);x.setAttribute('aria-selected',String(j===i))});const d=serviceData[i],box=document.querySelector('.service-display');box.animate([{opacity:.45,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:180});box.querySelector('.service-code').textContent=d.code;box.querySelector('h3').textContent=d.title;box.querySelector('.service-copy').textContent=d.copy;const labels=['We help','You receive','Typical first step'];box.querySelector('.service-meta').innerHTML=d.meta.map((x,j)=>`<span><b>${labels[j]}</b> ${x}</span>`).join('');box.querySelector('ul').innerHTML=d.items.map(x=>`<li>${x}</li>`).join('')}
const methodNodes=[...document.querySelectorAll('.manifesto article')];
function selectMethod(node){methodNodes.forEach(x=>{const active=x===node;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))})}
methodNodes.forEach((x,i)=>{x.tabIndex=0;x.setAttribute('role','tab');x.setAttribute('aria-selected',String(i===0));x.addEventListener('mouseenter',()=>selectMethod(x));x.addEventListener('focus',()=>selectMethod(x));x.addEventListener('click',()=>selectMethod(x));x.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?methodNodes.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+methodNodes.length)%methodNodes.length;methodNodes[next].focus()})});
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
const homeForm=document.querySelector('#contact-form');
if(homeForm){const messageLabel=homeForm.querySelector('textarea[name="message"]')?.closest('label');if(messageLabel)messageLabel.firstChild.textContent='Problem or context ';const preferred=homeForm.querySelector('select[name="preferred_contact"]')?.closest('label');preferred?.insertAdjacentHTML('beforebegin','<label>Urgency<select name="urgency"><option>Exploring</option><option>Within a few weeks</option><option>Time-sensitive</option></select></label>');homeForm.insertAdjacentHTML('afterend','<div class="contact-alternatives"><p><b>Privacy-first path:</b> You may describe the situation without naming the organization or people. Share only the return address you want us to use.</p><a class="pill quiet" href="mailto:info@anchorpoint.com.bd">Email us instead ↗</a></div>')}
if(!document.querySelector('#contact')&&document.querySelector('main')){
  document.body.insertAdjacentHTML('beforeend',`<dialog class="contact-dialog" id="contactDialog" aria-labelledby="contactDialogTitle"><form method="dialog" class="dialog-close-row"><button aria-label="Close contact form">Close ×</button></form><div class="contact-dialog-grid"><div><p class="kicker light"><span></span> Start with the difficulty</p><h2 id="contactDialogTitle">Request a response.</h2><p>No polished scope required. Share only non-confidential context.</p><p class="privacy-path">Prefer not to identify yourself yet? Describe the situation without names or organizations, and leave only the contact route you want us to use.</p><a class="email-secondary" href="mailto:info@anchorpoint.com.bd">Email us instead ↗</a></div><form class="contact-form-card" action="https://formspree.io/f/meajewyn" method="POST"><input type="hidden" name="_subject" value="New Anchor Point website enquiry"><label>Problem or context<textarea name="message" rows="5" required maxlength="1200" placeholder="What feels unclear, difficult or urgent?"></textarea></label><div class="contact-form-row"><label>Urgency<select name="urgency"><option>Exploring</option><option>Within a few weeks</option><option>Time-sensitive</option></select></label><label>Preferred response<select name="preferred_contact"><option>Email</option><option>Telephone</option></select></label></div><div class="contact-form-row"><label>Name <small>optional</small><input name="name" autocomplete="name" maxlength="100"></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="160"></label></div><label class="form-consent"><input type="checkbox" name="consent" value="yes" required><span>Anchor Point may use these details only to respond. I have not included confidential project information.</span></label><input class="form-honeypot" type="text" name="_gotcha" tabindex="-1" autocomplete="off" aria-hidden="true"><button class="pill gold" type="submit">Request a response ↗</button><p class="contact-form-note">Processed by Formspree. See the <a href="privacy.html#contact-enquiries">privacy notice</a>.</p></form></div></dialog>`);
  const dialog=document.querySelector('#contactDialog');
  document.querySelectorAll('a[href="index.html#contact"],a[href="#contact"],a[href^="mailto:"]').forEach(link=>{if(link.classList.contains('email-secondary'))return;link.addEventListener('click',e=>{e.preventDefault();dialog.showModal()})});
  dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
}
document.querySelector('.contact-card')?.insertAdjacentHTML('beforeend','<p style="font:italic .95rem/1.5 Playfair Display;color:var(--gold2);border-top:1px solid #ffffff18;padding-top:18px">A first conversation costs curiosity—not a procurement file. Start small. We are listening.</p>');
const principles=document.querySelector('.principles');if(document.querySelector('.hero')&&principles){principles.insertAdjacentHTML('afterend',`<section class="renaissance"><div class="renaissance-image" role="img" aria-label="Technical linework connecting marine, structural, mechanical, electrical, water and flight engineering"></div><div class="renaissance-copy reveal"><p class="kicker"><span></span> Curiosity is infrastructure</p><h2>A machine begins<br>as a question.</h2><p>Real projects do not respect departmental boundaries. Water affects structures. Operations affect machinery. People affect systems. Cost affects every option.</p><p>We observe closely, sketch freely, test honestly and connect what is usually considered separately.</p><p class="renaissance-note">A quiet Renaissance instinct: understand the world by drawing its connections.</p><a class="pill gold" href="#contact">Bring the napkin sketch, too ↗</a></div></section>`);document.querySelectorAll('.renaissance .reveal').forEach(el=>reveal.observe(el));}


