const header=document.querySelector('.topbar'),menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.addEventListener('click',()=>nav.classList.remove('open'));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)});
const serviceData=[
['AP / SERVICE 01','Feasibility & gap analysis','Before budgets harden, we map the real requirement, dependencies, failure paths, overlooked interfaces, and viable routes forward.',['Predominant-question framing','Requirement and interface mapping','Alternatives with consequences','Decision-ready recommendation']],
['AP / SERVICE 02','Technical due diligence','We independently interrogate specifications, proposals, reports, claims, risks, and lifecycle implications before your organization commits.',['Specification and offer review','Technical-commercial comparison','Risk and evidence register','Plain-language executive brief']],
['AP / SERVICE 03','Integration & delivery control','We keep disciplines, suppliers, interfaces, changes, inspections, commissioning, and handover moving as one accountable system.',['Cross-discipline coordination','Change and decision control','Inspection and commissioning support','Traceable handover record']],
['AP / SERVICE 04','International capability bridge','We translate local operating reality into precise global technical communication—and bring suitable expertise back into context.',['Vendor and specialist discovery','Technical communication bridge','Offer and capability evaluation','Local-global delivery coordination']]
];
document.querySelectorAll('.service-tabs button').forEach((btn,i)=>btn.addEventListener('click',()=>{document.querySelectorAll('.service-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=serviceData[i],box=document.querySelector('.service-display');box.animate([{opacity:.3,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350});box.querySelector('.service-code').textContent=d[0];box.querySelector('h3').textContent=d[1];box.querySelector('.service-copy').textContent=d[2];box.querySelector('ul').innerHTML=d[3].map(x=>`<li>${x}</li>`).join('')}));
document.querySelectorAll('.manifesto article').forEach(x=>x.addEventListener('mouseenter',()=>{document.querySelectorAll('.manifesto article').forEach(y=>y.classList.remove('active'));x.classList.add('active')}));
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
